config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from market.products.views import CategoryListView


urlpatterns = [
    url(r'^$', CategoryListView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^products/', include(("market.products.urls", "products"), namespace="products")),
    url(r'^users/', include(("market.users.urls", "users"), namespace="users")),
    url(r'^payments/', include(("market.payments.urls", "payments"), namespace="payments")),
    url(r'^myadmin/', include(("market.myadmin.urls", "myadmin"), namespace="myadmin")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

market/myadmin/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView


from rest_framework_nested import routers
from rest_framework_swagger.views import get_swagger_view


from market.myadmin.views import (
    OrderViewSet,
    OrderItemViewSet,
)


schema_view = get_swagger_view(title='Pastebin API')  # pylint: disable=invalid-name


simple_router = routers.SimpleRouter()

simple_router.register(r'orders', OrderViewSet, basename='orders')
simple_router.register(r'order_items', OrderItemViewSet, basename='order_items')


urlpatterns = [
    url(r'^', include(simple_router.urls)),
    url(r'^$', schema_view),
    url(r'^index/$', TemplateView.as_view(template_name='myadmin/index.html'), name='myadmin'),
]

market/products/urls.py
from django.conf.urls import url
from market.products import views


urlpatterns = [
    url(r'^info/$', views.InfoView.as_view(), name='info'),
    url(r'^search/$', views.search_products, name='search_products'),
    url(r'^cart/$', views.CartView.as_view(), name='cart'),
    url(r'^clear_cart/$', views.ClearCart.as_view(), name='clear_cart'),
    url(
        r'^(?P<product_pk>[0-9]+)/add/to/cart/$',
        views.AddToCartView.as_view(),
        name='add_to_cart'
    ),
    url(
        r'^(?P<category_slug>.+)/(?P<subcategory_slug>.+)/(?P<product_slug>.+)/$',
        views.ProductDetailView.as_view(),
        name='product_detail'
    ),
    url(
        r'^(?P<category_slug>.+)/(?P<subcategory_slug>.+)/$',
        views.SubCategoryDetailView.as_view(),
        name='subcategory_detail'),
]

market/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from market.users.views import RoomView, RegisterView

urlpatterns = [
    url(r'^room/$', RoomView.as_view(), name='room'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
]

market/blog/models.py
from django.db import models
from django.conf import settings

from pygments import highlight
from pygments.lexers import (
    PythonLexer,
    CLexer,
    CppLexer,
    BashLexer,
)

from pygments.formatters import HtmlFormatter


UserModel = settings.AUTH_USER_MODEL


class Post(models.Model):
    title = models.fields.CharField(max_length=255, null=False,
                                    blank=False)
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE,
                               blank=False, null=False,)
    text = models.fields.CharField(max_length=2000, null=False,
                                   blank=False)


class Snippet(models.Model):
    CODE_LANG = (
        ('c', 'c'),
        ('cpp', 'cpp'),
        ('python', 'python'),
        ('bash', 'bash'),
    )
    LEXERS = {
        'c': CLexer,
        'cpp': CppLexer,
        'python': PythonLexer,
        'bash': BashLexer,
    }

    lang = models.CharField(choices=CODE_LANG, default='python',
                            max_length=50, blank=False, null=False)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE,
        null=False, blank=False, related_name='snippets')
    code = models.CharField(max_length=2000, null=False,
                            blank=False)

    def __str__(self):
        formatted_code = highlight(self.code,
                                   self.LEXERS[str(self.lang)](),
                                   HtmlFormatter())
        return '%s\n%s' % (self.lang, formatted_code)

market/products/models.py
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone


from model_utils import Choices
from model_utils.models import TimeStampedModel

from ckeditor.fields import RichTextField
from config import settings


class Category(models.Model):
    """Product category model"""

    name = models.CharField(_('Name'), max_length=200)
    slug = models.SlugField(_('Slug'), unique=True)

    PARAMS = Choices(
        ('following', 'following'),
        ('price_to', 'price_to'),
        ('price_from', 'price_from'),
    )

    def __str__(self):
        return self.name
        

class SubCategory(models.Model):
    """Subcategory for category model"""

    name = models.CharField(max_length=200)
    slug = models.SlugField(_('Slug'), unique=True)

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='subcategories',
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            'products:subcategory_detail', 
            kwargs={
                'category_slug': self.category.slug,
                'subcategory_slug': self.slug
        })


class Product(TimeStampedModel):
    """Product model"""

    POPULAR_CHOICES = (
        ('F', 'not_popular'),
        ('T', 'popular')
    )

    name = models.CharField(_('Name'), max_length=200)
    code = models.CharField(
        null=False,
        blank=False,
        max_length=255,
    )
    in_stock = models.BooleanField(default=False)
    slug = models.SlugField(_('Slug'), unique=True)
    price = models.DecimalField(_('Price'), decimal_places=2, max_digits=9)
    description = RichTextField(_('Description'), blank=True)
    subcategory = models.ForeignKey(
        SubCategory,
        related_name='products',
        on_delete=models.CASCADE,
    )
    image = models.ImageField(upload_to='products', blank=True)
    popular = models.CharField(
        max_length=1,
        choices=POPULAR_CHOICES,
        blank=False,
        default='F',
    )
 
    class Meta:
        ordering = ('-created', )

    def get_absolute_url(self):
        return reverse('products:product_detail', kwargs={
            'category_slug': self.subcategory.category.slug,
            'subcategory_slug': self.subcategory.slug,
            'product_slug': self.slug
        })

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    image = models.ImageField(upload_to='products', blank=True)
    product = models.ForeignKey(
        Product,
        related_name='images',
        on_delete=models.CASCADE, 
    )


class Like(TimeStampedModel):
    product = models.ForeignKey(
        Product,
        related_name='likes',
        on_delete=models.CASCADE,         
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='likes',
        on_delete=models.CASCADE,     
    )

    class Meta:
        unique_together = (
            ('product', 'user'),
        )

    def __str__(self):
        return '{} from {}'.format(self.product, self.user)


class Comment(TimeStampedModel):
    product = models.ForeignKey(
        Product,
        blank=False,
        null=False,
        related_name='comments',
        on_delete=models.CASCADE,     
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=False,
        null=False,
        related_name='comments',
        on_delete=models.CASCADE, 
    )

    text = models.TextField(_('Comment'))


class Checkout(models.Model):
    phone = models.CharField(
        max_length=255,
        null=False,
        blank=False,
    )
    payment_type = models.CharField(
        max_length=30,
        choices=[
            ('stripe', 'Stripe'),
            ('paypal', 'PayPal'),
            ('liqpay', 'Liqpay')
        ],
        null=False,
        blank=False,
    )
    fio = models.CharField(
        max_length=255,
        null=True,
        blank=True,
    )
    email = models.EmailField(null=True)
    comment = models.CharField(
        max_length=500,
        null=False,
        blank=False,
    )

    def __str__(self):
        return 'Checkout({}, {}, {}, {}, {})'.format(
            self.pk,
            self.phone,
            self.fio,
            self.email,
            self.comment,
        )


class Order(TimeStampedModel):
    PAY_STRIPE = 'stripe'
    PAY_PAYPAL = 'paypal'
    PAY_LIQPAY = 'liqpay'

    DEFAULT_PAYMENT_TYPE = 'liqpay'

    total = models.DecimalField(
        _('Total'),
        decimal_places=2,
        max_digits=9,
    )
    paid = models.BooleanField(default=False)
    approved = models.BooleanField(default=False)
    payment_type = models.CharField(
        choices=[
            ('stripe', 'Stripe'),
            ('paypal', 'PayPal'),
            ('liqpay', 'Liqpay')
        ],
        max_length=255,
    )
    payment_id = models.CharField(
        blank=True,
        max_length=255,
    )
    u_id = models.CharField(
        blank=False,
        null=False,
        max_length=255,
    )
    json_response = JSONField(null=True, blank=True)
    checkout = models.ForeignKey(
        Checkout,
        on_delete=models.CASCADE,
        null=False,
    )

    progress = models.CharField(
        max_length=2,
        choices=(
            ('f', 'wait'),
            ('t', 'ok'),
        ),
        default='f',
    )
    datetime = models.DateTimeField(null=False, default=timezone.now())

    def __str__(self):
        return 'Order_{}'.format(self.pk)


class CartItem(TimeStampedModel):
    product = models.ForeignKey(
        Product,
        related_name='cart',
        on_delete=models.CASCADE,
    )
    order = models.ForeignKey(
        Order,
        related_name='cart_items',
        on_delete=models.CASCADE,
    )
    quantity = models.PositiveIntegerField(_('Amount'))
    total = models.DecimalField(
        _('Total'),
        decimal_places=2,
        max_digits=9,
    )

    def __str__(self):
        return 'CartItem for {}'.format(self.order)


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        related_name='items',
        on_delete=models.CASCADE,     
    )
    code = models.CharField(
        null=False,
        blank=False,
        max_length=255,
    )
    product = models.ForeignKey(
        Product,
        null=True,
        blank=True,
        related_name='+',
        on_delete=models.SET_NULL,
    )
    name = models.CharField(blank=False, null=False, max_length=200)
    price = models.DecimalField(_('Price'), decimal_places=2, max_digits=9)
    description = RichTextField(_('Description'), blank=True)
    subcategory = models.CharField(blank=False, null=False, max_length=200)

    quantity = models.PositiveIntegerField(_('Quantity'))
    total = models.DecimalField(_('Total'), decimal_places=2, max_digits=9)

market/payments/forms.py
from django import forms
from market.products.models import Checkout


class OrderForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    name = forms.CharField(max_length=50, required=True)
    surname = forms.CharField(max_length=50, required=True)
    phone = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(required=False)
    address = forms.CharField(max_length=255, required=True)


class CheckoutForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fio'].required = False
        self.fields['email'].required = False
        self.fields['comment'].required = True

    class Meta:
        model = Checkout
        fields = (
            'phone',
            'fio',
            'email',
            'comment',
            'payment_type'
        )

market/products/forms.py
from django import forms
from django.contrib.auth import get_user_model

from market.products.models import Product, Comment


User = get_user_model()


class LikeForm(forms.Form):
    user = forms.ModelChoiceField(
        User.objects.all(),
        required=False
    )
    product = forms.ModelChoiceField(Product.objects.all())


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['user', 'product', 'text']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'phone', 'email', 'password', 'image']
        widgets = {
            'username': forms.TextInput(attrs={
                'example': 'example',
                'class': 'wrap-input100 validate-input m-b-16 inputCustom',
                'placeholder': 'Укажите имя',
            }),
            'phone': forms.TextInput(attrs={
                'example': 'example',
                'class': 'wrap-input100 validate-input m-b-16 inputCustom',
                'placeholder': 'Укажите телефон',
            }),
            'email': forms.TextInput(attrs={
                'example': 'example',
                'class': 'wrap-input100 validate-input m-b-16 inputCustom',
                'placeholder': 'Укажите адрес эл.почты',
            }),
            'password': forms.TextInput(attrs={
                'type':'password',
                'example': 'example',
                'class': 'wrap-input100 validate-input m-b-16 inputCustom password_input',
                'placeholder': 'Пароль',
            }),
           
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

market/blog/views.py
from rest_framework.authentication import BasicAuthentication
from rest_framework import viewsets, views

from market.products.models import (
    Order,
    OrderItem,
)

from market.myadmin.pagination import StandardResultsSetPagination
from market.myadmin.permissions import IsAdminOrFYou
from market.myadmin.filters import (
    StatusFilterBackend,
    PaidStatusFilterBackend,
    OrderItemOrderPkFilterBackend,
)
from market.myadmin.serializers import (
    OrderSerializer,
    OrderItemSerializer,
)


class OrderViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderSerializer
    queryset = Order.objects.all()
    filter_backends = (
        StatusFilterBackend,
        PaidStatusFilterBackend
    )
    pagination_class = StandardResultsSetPagination

    def get_queryset(self, *arg, **kwargs):
        # from time import sleep
        # sleep(1)
        return super().get_queryset(*arg, **kwargs)


class OrderItemViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderItemSerializer
    queryset = OrderItem.objects.all()
    filter_backends = (
        OrderItemOrderPkFilterBackend,
    )
    pagination_class = StandardResultsSetPagination

market/myadmin/views.py
from rest_framework.authentication import BasicAuthentication
from rest_framework import viewsets, views

from market.products.models import (
    Order,
    OrderItem,
)

from market.myadmin.pagination import StandardResultsSetPagination
from market.myadmin.permissions import IsAdminOrFYou
from market.myadmin.filters import (
    StatusFilterBackend,
    PaidStatusFilterBackend,
    OrderItemOrderPkFilterBackend,
)
from market.myadmin.serializers import (
    OrderSerializer,
    OrderItemSerializer,
)


class OrderViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderSerializer
    queryset = Order.objects.all().order_by('-id')
    filter_backends = (
        StatusFilterBackend,
        PaidStatusFilterBackend
    )
    pagination_class = StandardResultsSetPagination

    def get_queryset(self, *arg, **kwargs):
        # from time import sleep
        # sleep(1)
        return super().get_queryset(*arg, **kwargs)


class OrderItemViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderItemSerializer
    queryset = OrderItem.objects.all()
    filter_backends = (
        OrderItemOrderPkFilterBackend,
    )
    pagination_class = StandardResultsSetPagination

market/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from django.views import generic
from django.urls import reverse_lazy
from config import settings

from market.products.forms import UserForm


class RoomView(LoginRequiredMixin, TemplateView):
    active_tab = 'cart'
    template_name = 'users/room.html'


class RegisterView(generic.CreateView):
    model = settings.AUTH_USER_MODEL
    form_class = UserForm
    success_url = reverse_lazy('users:login')
    template_name = 'register.html'

market/templates/additional_parts/products/amount_product_modal.html
<div class="modal fade" id="product_amount_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Choose amount of product</h4>
      </div>
      <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <input id="product_amount" type="number" value="1" class="form-control">
            </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" id="add_to_cart" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</div>

market/templates/additional_parts/products/cart_checkout_modal.html
<div class="modal fade" id="cart_checkout_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Заполните форму заказа</h4>
      </div>
      <div class="modal-body">
          <form method="post" action="{% url 'payments:order_list' %}">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-12">
                    {{ form.non_field_errors }}
                    <div class="row">
                        <div class="col-md-6">
                            {{ order_form.name.errors }}
                            <label for="id_name">Name:</label>
                            {{ order_form.name }}
                        </div>
                        <div class="col-md-6">
                            {{ order_form.surname.errors }}
                            <label for="id_surname">Surname:</label>
                            {{ order_form.surname }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            {{ order_form.phone.errors }}
                            <label for="id_phone">Phone:</label>
                            {{ order_form.phone }}
                        </div>
                       <div class="col-md-6">
                            {{ order_form.email.errors }}
                            <label for="id_email">Email:</label>
                            {{ order_form.email }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            {{ order_form.address.errors }}
                            <label for="id_address">Address:</label>
                            {{ order_form.address }}
                        </div>
                    </div>
                </div>
            </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" id="checkout_btn" class="btn btn-primary">Submit</button>
              </div>
          </form>
      </div>
    </div>
  </div>
</div>

market/templates/additional_parts/products/pagination.html
<div class="row">
    <div class="col-md-4 center-align">
        {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}
    </div>
</div>

market/templates/additional_parts/products/product_detail_comment.html
{% load thumbnail %}
 <div class="otziv_user">  
    <div class="foto_user">
        {% thumbnail comment.user.image "80x267" as im %}
             <img src="{{ im.url }}" class="img_product_detail">
        {% endthumbnail %}
    </div>
    <div class="text_otziv">
             <h3 class="name_user">{{ comment.user.username }}</h3>
             <p class="otziv_user_text">{{ comment.text }}</p>
             <div class="riska_otziv"></div>
             <h6 class="data_otziv">{{ comment.created.year }}/
                    {{ comment.created.month }}/
                    {{ comment.created.day }}
            </h6>
    </div>
</div>

market/templates/additional_parts/products/products_list_imagination.html
{% load thumbnail %}
{% for product in products %}
<div class="single__list__content clearfix">
    <div class="col-md-3 col-lg-3 col-sm-4 col-xs-12">
        <div class="list__thumb">
            <a href="{{ product.get_absolute_url }}">
                {% thumbnail product.image "770x270" as im %}
                    <img src="{{ im.url }}" alt="product images">
                {% endthumbnail %}
            </a>
        </div>
    </div>
    <div class="col-md-9 col-lg-9 col-sm-8 col-xs-12">
        <div class="list__details__inner">
            <h2><a href="{{ product.get_absolute_url }}">{{ product.name | title}}</a></h2>
            <p>{{ product.description | safe }}</p>
            <span class="product__price">${{ product.price }}</span>
            <div class="shop__btn">
                <a class="htc__btn" href="{% url 'products:add_to_cart' product.pk %}"><span class="ti-shopping-cart"></span>Add to Cart</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}

market/templates/additional_parts/products/quick_view_modal.html
{% load thumbnail %}
{% for product in products %}
<div class="modal fade" id="productModal_{{ product.pk }}" tabindex="-1" role="dialog">
        <div class="modal-dialog modal__container" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <div class="modal-product">
                        <!-- Start product images -->
                        <div class="product-images">
                            <div class="main-image images">
                                {% thumbnail product.image "600x600" as im %}
                                    <img src="{{ im.url }}" alt="big image">
                                {% endthumbnail %}
                            </div>
                        </div>
                        <!-- end product images -->
                        <div class="product-info">
                            <h1>Simple Fabric Bags</h1>
                            <div class="rating__and__review">
                                <ul class="rating">
                                    <li><span class="ti-star"></span></li>
                                    <li><span class="ti-star"></span></li>
                                    <li><span class="ti-star"></span></li>
                                    <li><span class="ti-star"></span></li>
                                    <li><span class="ti-star"></span></li>
                                </ul>
                                <div class="review">
                                    <a href="#">4 customer reviews</a>
                                </div>
                            </div>
                            <div class="price-box-3">
                                <div class="s-price-box">
                                    <span class="new-price">${{ product.price }}</span>
                                    <span class="old-price">${{ product.price }}</span>
                                </div>
                            </div>
                            <div class="quick-desc">
                                {{ product.description | safe }}
                            </div>
                            <div class="select__color">
                                <h2>Select color</h2>
                                <ul class="color__list">
                                    <li class="red"><a title="Red" href="#">Red</a></li>
                                    <li class="gold"><a title="Gold" href="#">Gold</a></li>
                                    <li class="orange"><a title="Orange" href="#">Orange</a></li>
                                    <li class="orange"><a title="Orange" href="#">Orange</a></li>
                                </ul>
                            </div>
                            <div class="select__size">
                                <h2>Select size</h2>
                                <ul class="color__list">
                                    <li class="l__size"><a title="L" href="#">L</a></li>
                                    <li class="m__size"><a title="M" href="#">M</a></li>
                                    <li class="s__size"><a title="S" href="#">S</a></li>
                                    <li class="xl__size"><a title="XL" href="#">XL</a></li>
                                    <li class="xxl__size"><a title="XXL" href="#">XXL</a></li>
                                </ul>
                            </div>
                            <div class="social-sharing">
                                <div class="widget widget_socialsharing_widget">
                                    <h3 class="widget-title-modal">Share this product</h3>
                                    <ul class="social-icons">
                                        <li><a target="_blank" title="rss" href="#" class="rss social-icon"><i class="zmdi zmdi-rss"></i></a></li>
                                        <li><a target="_blank" title="Linkedin" href="#" class="linkedin social-icon"><i class="zmdi zmdi-linkedin"></i></a></li>
                                        <li><a target="_blank" title="Pinterest" href="#" class="pinterest social-icon"><i class="zmdi zmdi-pinterest"></i></a></li>
                                        <li><a target="_blank" title="Tumblr" href="#" class="tumblr social-icon"><i class="zmdi zmdi-tumblr"></i></a></li>
                                        <li><a target="_blank" title="Pinterest" href="#" class="pinterest social-icon"><i class="zmdi zmdi-pinterest"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="addtocart-btn">
                                <a href="{% url 'products:add_to_cart' product.pk %}">Add to cart</a>
                            </div>
                        </div><!-- .product-info -->
                    </div><!-- .modal-product -->
                </div><!-- .modal-body -->
            </div><!-- .modal-content -->
        </div><!-- .modal-dialog -->
    </div>
{% endfor %}