config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from market.products.views import CategoryListView


urlpatterns = [
    url(r'^$', CategoryListView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^products/', include(("market.products.urls", "products"), namespace="products")),
    url(r'^users/', include(("market.users.urls", "users"), namespace="users")),
    url(r'^payments/', include(("market.payments.urls", "payments"), namespace="payments")),
    url(r'^myadmin/', include(("market.myadmin.urls", "myadmin"), namespace="myadmin")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

market/myadmin/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView


from rest_framework_nested import routers
from rest_framework_swagger.views import get_swagger_view


from market.myadmin.views import (
    OrderViewSet,
    OrderItemViewSet,
)


schema_view = get_swagger_view(title='Pastebin API')  # pylint: disable=invalid-name


simple_router = routers.SimpleRouter()

simple_router.register(r'orders', OrderViewSet, basename='orders')
simple_router.register(r'order_items', OrderItemViewSet, basename='order_items')


urlpatterns = [
    url(r'^', include(simple_router.urls)),
    url(r'^$', schema_view),
    url(r'^index/$', TemplateView.as_view(template_name='myadmin/index.html'), name='myadmin'),
]

market/payments/urls.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from market.payments import views


urlpatterns = [
    url(r'^checkout/$', views.CheckoutView.as_view(), name='checkout'),
    url(r'^orders/$', views.OrderListView.as_view(), name='orders'),
    url(r'^paystripe/(?P<pk>[0-9]+)/$', views.PayStripeView.as_view(), name='pay_stripe'),
    url(r'^paypal/(?P<pk>[0-9]+)/$', views.PayPalView.as_view(), name='pay_paypal'),
    url(r'^paypal/execute/$', views.PayPalExecuteView.as_view(), name='paypal_execute'),
    url(r'^pay/(?P<pk>[0-9]+)/$$', views.PayView.as_view(), name='pay_liqpay'),
    url(r'^pay-callback/$', views.PayCallbackView.as_view(), name='pay_liqpay_callback'),
]

market/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from market.users.views import RoomView, RegisterView

urlpatterns = [
    url(r'^room/$', RoomView.as_view(), name='room'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
]

market/blog/models.py
from django.db import models
from django.conf import settings

from pygments import highlight
from pygments.lexers import (
    PythonLexer,
    CLexer,
    CppLexer,
    BashLexer,
)

from pygments.formatters import HtmlFormatter


UserModel = settings.AUTH_USER_MODEL


class Post(models.Model):
    title = models.fields.CharField(max_length=255, null=False,
                                    blank=False)
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE,
                               blank=False, null=False,)
    text = models.fields.CharField(max_length=2000, null=False,
                                   blank=False)


class Snippet(models.Model):
    CODE_LANG = (
        ('c', 'c'),
        ('cpp', 'cpp'),
        ('python', 'python'),
        ('bash', 'bash'),
    )
    LEXERS = {
        'c': CLexer,
        'cpp': CppLexer,
        'python': PythonLexer,
        'bash': BashLexer,
    }

    lang = models.CharField(choices=CODE_LANG, default='python',
                            max_length=50, blank=False, null=False)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE,
        null=False, blank=False, related_name='snippets')
    code = models.CharField(max_length=2000, null=False,
                            blank=False)

    def __str__(self):
        formatted_code = highlight(self.code,
                                   self.LEXERS[str(self.lang)](),
                                   HtmlFormatter())
        return '%s\n%s' % (self.lang, formatted_code)

market/models.py
from django.db import models

# Create your models here.

market/payments/forms.py
from django import forms
from market.products.models import Checkout


class OrderForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    name = forms.CharField(max_length=50, required=True)
    surname = forms.CharField(max_length=50, required=True)
    phone = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(required=False)
    address = forms.CharField(max_length=255, required=True)


class CheckoutForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fio'].required = False
        self.fields['email'].required = False
        self.fields['comment'].required = True

    class Meta:
        model = Checkout
        fields = (
            'phone',
            'fio',
            'email',
            'comment',
            'payment_type'
        )

market/blog/views.py
from rest_framework.authentication import BasicAuthentication
from rest_framework import viewsets, views

from market.products.models import (
    Order,
    OrderItem,
)

from market.myadmin.pagination import StandardResultsSetPagination
from market.myadmin.permissions import IsAdminOrFYou
from market.myadmin.filters import (
    StatusFilterBackend,
    PaidStatusFilterBackend,
    OrderItemOrderPkFilterBackend,
)
from market.myadmin.serializers import (
    OrderSerializer,
    OrderItemSerializer,
)


class OrderViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderSerializer
    queryset = Order.objects.all()
    filter_backends = (
        StatusFilterBackend,
        PaidStatusFilterBackend
    )
    pagination_class = StandardResultsSetPagination

    def get_queryset(self, *arg, **kwargs):
        # from time import sleep
        # sleep(1)
        return super().get_queryset(*arg, **kwargs)


class OrderItemViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderItemSerializer
    queryset = OrderItem.objects.all()
    filter_backends = (
        OrderItemOrderPkFilterBackend,
    )
    pagination_class = StandardResultsSetPagination

market/myadmin/views.py
from rest_framework.authentication import BasicAuthentication
from rest_framework import viewsets, views

from market.products.models import (
    Order,
    OrderItem,
)

from market.myadmin.pagination import StandardResultsSetPagination
from market.myadmin.permissions import IsAdminOrFYou
from market.myadmin.filters import (
    StatusFilterBackend,
    PaidStatusFilterBackend,
    OrderItemOrderPkFilterBackend,
)
from market.myadmin.serializers import (
    OrderSerializer,
    OrderItemSerializer,
)


class OrderViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderSerializer
    queryset = Order.objects.all().order_by('-id')
    filter_backends = (
        StatusFilterBackend,
        PaidStatusFilterBackend
    )
    pagination_class = StandardResultsSetPagination

    def get_queryset(self, *arg, **kwargs):
        # from time import sleep
        # sleep(1)
        return super().get_queryset(*arg, **kwargs)


class OrderItemViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderItemSerializer
    queryset = OrderItem.objects.all()
    filter_backends = (
        OrderItemOrderPkFilterBackend,
    )
    pagination_class = StandardResultsSetPagination

market/payments/views.py
import uuid

from django.views.generic import TemplateView, ListView, View
from django.views.generic.detail import (
    SingleObjectMixin,
    SingleObjectTemplateResponseMixin,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.shortcuts import render, HttpResponse
from django.http import Http404

from market.products.models import CartItem, OrderItem
from market.products.cart import Cart
from market.payments.tasks import purchase_mailing


import stripe
import paypalrestsdk
from liqpay import LiqPay


from market.products.models import (
    Order,
)

from market.payments.forms import CheckoutForm
from market.common.utils import (
    get_carts_total,
    create_order_items,
    create_paypal_payment_data,
)

from config import settings
from config.settings import paypal_api


PAYMENT_VIEWS = {
    Order.PAY_STRIPE: 'payments:pay_stripe',
    Order.PAY_PAYPAL: 'payments:pay_paypal',
    Order.PAY_LIQPAY: 'payments:pay_liqpay'
}


class CheckoutView(TemplateView):
    template_name = 'payments/checkout.html'

    def get(self, request, *args, **kwargs):
        return render(
            request,
            self.template_name,
            {
                'checkout_form': CheckoutForm()
            }
        )

    def post(self, request, *args, **kwargs):
        checkout_form = CheckoutForm(request.POST)
        if not checkout_form.is_valid():
            return render(
                request,
                self.template_name,
                {
                    'checkout_form': checkout_form
                }
            )
        cleaned_checkout_data = checkout_form.cleaned_data
        checkout = checkout_form.save()

        payment_type = cleaned_checkout_data.get('payment_type')
        cart = Cart(self.request)

        order = Order.objects.create(
            total=cart.get_total_price(),
            payment_type=payment_type,
            u_id=str(uuid.uuid4()),
            checkout=checkout,
        )
        order_items = [
            OrderItem.objects.create(
                order=order,
                product=product,
                name=product.name,
                code=product.code,
                price=product.price,
                description=product.description,
                subcategory=product.subcategory.name,
                quantity=product.quantity,
                total=product.total_price,
            )
            for product in cart.get_products()
        ]

        try:
            url_name = PAYMENT_VIEWS[payment_type]
        except KeyError:
            raise

        return redirect(
            reverse(
                url_name,
                kwargs={
                    'pk': order.pk
                }
            )
        )


class OrderListView(ListView):
    template_name = 'payments/order_list.html'
    model = Order
    context_object_name = 'order_list'

    def get_queryset(self):
        return super().get_queryset().filter(
            user=self.request.user,
            paid=False,
        )


class PaymentView(SingleObjectTemplateResponseMixin, SingleObjectMixin, View):
    model = Order
    context_object_name = 'order'

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order_items'] = self.object.items.all().select_related('product')
        return context


class PayStripeView(PaymentView):
    template_name = 'payments/pay_stripe.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stripe_public_key'] = settings.STRIPE_PUBLIC_KEY
        context['total_cent'] = self.object.total * 100

        return context

    def post(self, request, *args, **kwargs):
        token = request.POST.get('stripeToken')
        order = self.get_object()
        charge = stripe.Charge.create(
            amount=int(order.total),
            currency='usd',
            description='Example charge',
            source=token,
        )
        charge.save()

        order.paid = True
        order.payment_type = Order.PAY_STRIPE
        order.payment_id = charge['id']

        order.save(update_fields=[
            'payment_type',
            'payment_id',
            'paid',
        ])
        purchase_mailing.delay(self.request.user.email, order.pk)
        return HttpResponseRedirect(reverse('home'))


class PayPalView(PaymentView):
    template_name = 'payments/pay_paypal.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client_id'] = settings.PAYPAL_CLIENT_ID
        return context

    def post(self, request, *args, **kwargs):
        order = self.get_object()
        order_items = order.items.all().select_related('product')
        payment_data = create_paypal_payment_data(order_items, order)
        payment = paypalrestsdk.Payment(payment_data, api=paypal_api)
        if payment.create():
            order.payment_type = Order.PAY_PAYPAL
            order.payment_id = payment.id
            order.save(update_fields=['payment_type', 'payment_id'])
            
            return JsonResponse({
                'paymentID': payment.id
            })
        
        return JsonResponse({
            'paymentID': None
        })


class PayPalExecuteView(View):

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, *args, **kwargs):
        order = Order.objects.get(
            payment_type=Order.PAY_PAYPAL,
            payment_id=self.request.POST.get('paymentID'),
        )
        payment = paypalrestsdk.Payment.find(self.request.POST.get('paymentID'))
        if payment.execute({'payer_id': self.request.POST.get('payerID')}):
            order.paid = True
            order.save(update_fields=['paid'])
            purchase_mailing.delay(self.request.user.email, order.pk)
            return JsonResponse({
                'payment_status': 'ok'
            })
        return JsonResponse({
            'payment_status': 'fail'
        })


class PayView(PaymentView):
    template_name = 'payments/pay_liqpay.html'

    def get(self, request, *args, **kwargs):
        liqpay = LiqPay(settings.LIQPAY_PUBLIC_KEY, settings.LIQPAY_PRIVATE_KEY)
        order = self.get_object()
        if order.paid:
            return HttpResponse("HTTP 403 status code. Restricted Area", status=403)

        params = {
            'action': 'pay',
            'amount': str(order.total),
            'currency': 'UAH',
            'description': 'Покупка электроники',
            'order_id': order.u_id,
            'version': '3',
            'sandbox': 0, # sandbox mode, set to 1 to enable it
            'server_url': settings.LIQPAY_CALLBACK_URL, # url to callback view
        }
        signature = liqpay.cnb_signature(params)
        data = liqpay.cnb_data(params)

        return render(
            request,
            self.template_name,
            {
                'signature': signature,
                'data': data,
                'order': order,
            }
        )


@method_decorator(csrf_exempt, name='dispatch')
class PayCallbackView(View):

    def post(self, request, *args, **kwargs):
        liqpay = LiqPay(settings.LIQPAY_PUBLIC_KEY, settings.LIQPAY_PRIVATE_KEY)
        data = request.POST.get('data')
        signature = request.POST.get('signature')

        sign = liqpay.str_to_sign(settings.LIQPAY_PRIVATE_KEY + data + settings.LIQPAY_PRIVATE_KEY)
        if sign == signature:
            response = liqpay.decode_data_from_str(data)
            order = Order.objects.get(u_id=response['order_id'])
            order.json_response = response
            status = response['status']
            if status == 'success' or \
                    status == 'wait_accept' or \
                    status == 'wait_compensation':
                order.paid = True
                order.payment_id = response['payment_id']
                order.save()
                return HttpResponse('ok')

            order.save()
            return HttpResponse('payment error: see detail', code=405)

        return HttpResponse('signature error', code=405)

market/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from django.views import generic
from django.urls import reverse_lazy
from config import settings

from market.products.forms import UserForm


class RoomView(LoginRequiredMixin, TemplateView):
    active_tab = 'cart'
    template_name = 'users/room.html'


class RegisterView(generic.CreateView):
    model = settings.AUTH_USER_MODEL
    form_class = UserForm
    success_url = reverse_lazy('users:login')
    template_name = 'register.html'

market/templates/payments/checkout.html
{% extends 'base.html' %}


{% block content %}
<div class="border_order">
    <h3 class="checkout_h">Оформление заказа</h3>
</div>
<form action="{% url 'payments:checkout' %}" method="post" class="checkout_form">
    {% csrf_token %}
    {% for field in checkout_form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
    {% endfor %}
    <input type="submit" value="КУПИТЬ" class="submit_checkout">
</form>
{% endblock content %}

market/templates/payments/order_list.html
{% extends 'base.html' %}

{% block content %}
    <h4>order list</h4>
    {% for order in order_list %}
        <div class="row">
            <div class="col-md-2">
                id - {{ order.pk }}                
            </div>
            <div class="col-md-2">
                total - {{ order.total }}
            </div>
            <div class="col-md-2">

                <a href="{% if order.payment_type == 'stripe' %}
                            {% url 'payments:pay_stripe' order.pk %}
                          {% elif order.payment_type == 'paypal' %}
                            {% url 'payments:pay_paypal' order.pk %}
                          {%  endif %}
                           ">
                    <button class="btn btn-primary">
                        Complete transaction
                    </button>
                </a>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

market/templates/payments/pay_liqpay.html
{% extends 'base.html' %}

{% block content %}
    {% for order_item in order_items %}
        <div class="row">
            <div class="col-md-3">
                {{ order_item.product.name }}
            </div>
            <div class="col-md-3">
                {{ order_item.price }}
            </div>
            <div class="col-md-3">
                {{ order_item.amount}}
            </div>
            <div class="col-md-3">
                {{ order_item.total }}
            </div>
        </div>
    {% endfor %}
    <div id="liqpay_checkout"></div>
    <div id="aft_payment_info"></div>
    <script>
    window.LiqPayCheckoutCallback = function() {
        LiqPayCheckout.init({
            data: "{{ data }}",
            signature: "{{ signature }}",
            embedTo: "#liqpay_checkout",
            mode: "embed" // embed || popup,
        }).on("liqpay.callback", function(data){
            console.log(data.status);
            console.log(data);
            $('#aft_payment_info').html("<h3>Ваш заказ уже обрабатываеться. В течении часа с вами свяжеться наш оператор по номеру который вы указали в заявке.</h3><a href='/'>На главную</a>");
            send_ajax_request("/products/clear_cart/", {}, clear_cart_response, "DELETE", "json");
        }).on("liqpay.ready", function(data){
            // ready
        }).on("liqpay.close", function(data){
            // close
        });
    };
    </script>
    <script src="//static.liqpay.ua/libjs/checkout.js" async></script>
{% endblock content %}

market/templates/payments/pay_paypal.html
{% extends 'base.html' %}

{% block content %}
    <h4>
        pay paypal
    </h4>
<div id="paypal-button-container"></div>
{% endblock content %}

{% block javascript %}
<script src="https://www.paypalobjects.com/api/checkout.js"></script>
<script>
paypal.Button.render({

        env: 'sandbox', // sandbox | production

        // Show the buyer a 'Pay Now' button in the checkout flow
        commit: true,

        // payment() is called when the button is clicked
        payment: function() {

            // Set up a url on your server to create the payment
            var CREATE_URL = '{% url 'payments:pay_paypal' order.pk %}';

            // Make a call to your server to set up the payment
            return paypal.request.post(CREATE_URL)
                .then(function(res) {

                    console.log(res);
                    return res.paymentID;
                });
        },

        // onAuthorize() is called when the buyer approves the payment
        onAuthorize: function(data, actions) {

            // Set up a url on your server to execute the payment
            var EXECUTE_URL = '{% url 'payments:paypal_execute' %}';

            // Set up the data you need to pass to your server
            var data = {
                paymentID: data.paymentID,
                payerID: data.payerID
            };

            // Make a call to your server to execute the payment
            return paypal.request.post(EXECUTE_URL, data)
                .then(function (res) {
                    console.log(res);
                });
        }

    }, '#paypal-button-container');



function send_ajax_request(request_url, data, success_func) {
        console.log('ajax function');
        $.ajax({
            url: request_url,
            type: 'POST',
            dataType: 'json',
            data: data,
            success: function(ajax_response) {
                success_func(ajax_response);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                   console.log(xhr.status);
                console.log(thrownError);
            }
        });
    }

function sendPaymentData(data) {
    var request_url = '{% url 'payments:pay_paypal' order.pk %}';
    send_ajax_request(request_url, data, payPalOK);
}

function payPalOK(data) {
    console.log(data);
    return data.paymentID;
}

</script>

{% endblock javascript %}

market/templates/payments/pay_stripe.html
{% extends 'base.html' %}

{% block content %}
    <h4>
        pay stripe
    </h4>
    {% for order_item in order_items %}
        <div class="row">
            <div class="col-md-3">
                {{ order_item.product.name }}
            </div>
            <div class="col-md-3">
                {{ order_item.price }}
            </div>
            <div class="col-md-3">
                {{ order_item.amount}}
            </div>
            <div class="col-md-3">
                {{ order_item.total }}
            </div>
        </div>
    {% endfor %}
    <div class="row">
        <div class="col-md-2">
            Total - {{ order.total }}
        </div>
    </div>
    <form action="{% url 'payments:pay_stripe' order.pk %}" method="POST">
      {% csrf_token %}
      <script
        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="{{ stripe_public_key }}"
        data-amount="{{ total_cent }}"
        data-name="Stripe.com"
        data-description="Example charge"
        data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
        data-locale="auto"
        data-zip-code="true">
      </script>
    </form>
{% endblock content %}