config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from market.products.views import CategoryListView


urlpatterns = [
    url(r'^$', CategoryListView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^products/', include(("market.products.urls", "products"), namespace="products")),
    url(r'^users/', include(("market.users.urls", "users"), namespace="users")),
    url(r'^payments/', include(("market.payments.urls", "payments"), namespace="payments")),
    url(r'^myadmin/', include(("market.myadmin.urls", "myadmin"), namespace="myadmin")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

market/myadmin/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView


from rest_framework_nested import routers
from rest_framework_swagger.views import get_swagger_view


from market.myadmin.views import (
    OrderViewSet,
    OrderItemViewSet,
)


schema_view = get_swagger_view(title='Pastebin API')  # pylint: disable=invalid-name


simple_router = routers.SimpleRouter()

simple_router.register(r'orders', OrderViewSet, basename='orders')
simple_router.register(r'order_items', OrderItemViewSet, basename='order_items')


urlpatterns = [
    url(r'^', include(simple_router.urls)),
    url(r'^$', schema_view),
    url(r'^index/$', TemplateView.as_view(template_name='myadmin/index.html'), name='myadmin'),
]

market/payments/urls.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from market.payments import views


urlpatterns = [
    url(r'^checkout/$', views.CheckoutView.as_view(), name='checkout'),
    url(r'^orders/$', views.OrderListView.as_view(), name='orders'),
    url(r'^paystripe/(?P<pk>[0-9]+)/$', views.PayStripeView.as_view(), name='pay_stripe'),
    url(r'^paypal/(?P<pk>[0-9]+)/$', views.PayPalView.as_view(), name='pay_paypal'),
    url(r'^paypal/execute/$', views.PayPalExecuteView.as_view(), name='paypal_execute'),
    url(r'^pay/(?P<pk>[0-9]+)/$$', views.PayView.as_view(), name='pay_liqpay'),
    url(r'^pay-callback/$', views.PayCallbackView.as_view(), name='pay_liqpay_callback'),
]

market/products/urls.py
from django.conf.urls import url
from market.products import views


urlpatterns = [
    url(r'^info/$', views.InfoView.as_view(), name='info'),
    url(r'^search/$', views.search_products, name='search_products'),
    url(r'^cart/$', views.CartView.as_view(), name='cart'),
    url(r'^clear_cart/$', views.ClearCart.as_view(), name='clear_cart'),
    url(
        r'^(?P<product_pk>[0-9]+)/add/to/cart/$',
        views.AddToCartView.as_view(),
        name='add_to_cart'
    ),
    url(
        r'^(?P<category_slug>.+)/(?P<subcategory_slug>.+)/(?P<product_slug>.+)/$',
        views.ProductDetailView.as_view(),
        name='product_detail'
    ),
    url(
        r'^(?P<category_slug>.+)/(?P<subcategory_slug>.+)/$',
        views.SubCategoryDetailView.as_view(),
        name='subcategory_detail'),
]

market/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from market.users.views import RoomView, RegisterView

urlpatterns = [
    url(r'^room/$', RoomView.as_view(), name='room'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
]

market/models.py
from django.db import models

# Create your models here.

market/myadmin/models.py
from django.db import models

# Create your models here.

market/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    image = models.ImageField(upload_to='users', blank=True)
    phone = models.CharField(blank=False,
                             null=False,
                             max_length=20)
    
    def __str__(self):
        return self.username

market/payments/forms.py
from django import forms
from market.products.models import Checkout


class OrderForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    name = forms.CharField(max_length=50, required=True)
    surname = forms.CharField(max_length=50, required=True)
    phone = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(required=False)
    address = forms.CharField(max_length=255, required=True)


class CheckoutForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fio'].required = False
        self.fields['email'].required = False
        self.fields['comment'].required = True

    class Meta:
        model = Checkout
        fields = (
            'phone',
            'fio',
            'email',
            'comment',
            'payment_type'
        )

market/blog/views.py
from rest_framework.authentication import BasicAuthentication
from rest_framework import viewsets, views

from market.products.models import (
    Order,
    OrderItem,
)

from market.myadmin.pagination import StandardResultsSetPagination
from market.myadmin.permissions import IsAdminOrFYou
from market.myadmin.filters import (
    StatusFilterBackend,
    PaidStatusFilterBackend,
    OrderItemOrderPkFilterBackend,
)
from market.myadmin.serializers import (
    OrderSerializer,
    OrderItemSerializer,
)


class OrderViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderSerializer
    queryset = Order.objects.all()
    filter_backends = (
        StatusFilterBackend,
        PaidStatusFilterBackend
    )
    pagination_class = StandardResultsSetPagination

    def get_queryset(self, *arg, **kwargs):
        # from time import sleep
        # sleep(1)
        return super().get_queryset(*arg, **kwargs)


class OrderItemViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderItemSerializer
    queryset = OrderItem.objects.all()
    filter_backends = (
        OrderItemOrderPkFilterBackend,
    )
    pagination_class = StandardResultsSetPagination

market/myadmin/views.py
from rest_framework.authentication import BasicAuthentication
from rest_framework import viewsets, views

from market.products.models import (
    Order,
    OrderItem,
)

from market.myadmin.pagination import StandardResultsSetPagination
from market.myadmin.permissions import IsAdminOrFYou
from market.myadmin.filters import (
    StatusFilterBackend,
    PaidStatusFilterBackend,
    OrderItemOrderPkFilterBackend,
)
from market.myadmin.serializers import (
    OrderSerializer,
    OrderItemSerializer,
)


class OrderViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderSerializer
    queryset = Order.objects.all().order_by('-id')
    filter_backends = (
        StatusFilterBackend,
        PaidStatusFilterBackend
    )
    pagination_class = StandardResultsSetPagination

    def get_queryset(self, *arg, **kwargs):
        # from time import sleep
        # sleep(1)
        return super().get_queryset(*arg, **kwargs)


class OrderItemViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderItemSerializer
    queryset = OrderItem.objects.all()
    filter_backends = (
        OrderItemOrderPkFilterBackend,
    )
    pagination_class = StandardResultsSetPagination

market/payments/views.py
import uuid

from django.views.generic import TemplateView, ListView, View
from django.views.generic.detail import (
    SingleObjectMixin,
    SingleObjectTemplateResponseMixin,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.shortcuts import render, HttpResponse
from django.http import Http404

from market.products.models import CartItem, OrderItem
from market.products.cart import Cart
from market.payments.tasks import purchase_mailing


import stripe
import paypalrestsdk
from liqpay import LiqPay


from market.products.models import (
    Order,
)

from market.payments.forms import CheckoutForm
from market.common.utils import (
    get_carts_total,
    create_order_items,
    create_paypal_payment_data,
)

from config import settings
from config.settings import paypal_api


PAYMENT_VIEWS = {
    Order.PAY_STRIPE: 'payments:pay_stripe',
    Order.PAY_PAYPAL: 'payments:pay_paypal',
    Order.PAY_LIQPAY: 'payments:pay_liqpay'
}


class CheckoutView(TemplateView):
    template_name = 'payments/checkout.html'

    def get(self, request, *args, **kwargs):
        return render(
            request,
            self.template_name,
            {
                'checkout_form': CheckoutForm()
            }
        )

    def post(self, request, *args, **kwargs):
        checkout_form = CheckoutForm(request.POST)
        if not checkout_form.is_valid():
            return render(
                request,
                self.template_name,
                {
                    'checkout_form': checkout_form
                }
            )
        cleaned_checkout_data = checkout_form.cleaned_data
        checkout = checkout_form.save()

        payment_type = cleaned_checkout_data.get('payment_type')
        cart = Cart(self.request)

        order = Order.objects.create(
            total=cart.get_total_price(),
            payment_type=payment_type,
            u_id=str(uuid.uuid4()),
            checkout=checkout,
        )
        order_items = [
            OrderItem.objects.create(
                order=order,
                product=product,
                name=product.name,
                code=product.code,
                price=product.price,
                description=product.description,
                subcategory=product.subcategory.name,
                quantity=product.quantity,
                total=product.total_price,
            )
            for product in cart.get_products()
        ]

        try:
            url_name = PAYMENT_VIEWS[payment_type]
        except KeyError:
            raise

        return redirect(
            reverse(
                url_name,
                kwargs={
                    'pk': order.pk
                }
            )
        )


class OrderListView(ListView):
    template_name = 'payments/order_list.html'
    model = Order
    context_object_name = 'order_list'

    def get_queryset(self):
        return super().get_queryset().filter(
            user=self.request.user,
            paid=False,
        )


class PaymentView(SingleObjectTemplateResponseMixin, SingleObjectMixin, View):
    model = Order
    context_object_name = 'order'

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order_items'] = self.object.items.all().select_related('product')
        return context


class PayStripeView(PaymentView):
    template_name = 'payments/pay_stripe.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stripe_public_key'] = settings.STRIPE_PUBLIC_KEY
        context['total_cent'] = self.object.total * 100

        return context

    def post(self, request, *args, **kwargs):
        token = request.POST.get('stripeToken')
        order = self.get_object()
        charge = stripe.Charge.create(
            amount=int(order.total),
            currency='usd',
            description='Example charge',
            source=token,
        )
        charge.save()

        order.paid = True
        order.payment_type = Order.PAY_STRIPE
        order.payment_id = charge['id']

        order.save(update_fields=[
            'payment_type',
            'payment_id',
            'paid',
        ])
        purchase_mailing.delay(self.request.user.email, order.pk)
        return HttpResponseRedirect(reverse('home'))


class PayPalView(PaymentView):
    template_name = 'payments/pay_paypal.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client_id'] = settings.PAYPAL_CLIENT_ID
        return context

    def post(self, request, *args, **kwargs):
        order = self.get_object()
        order_items = order.items.all().select_related('product')
        payment_data = create_paypal_payment_data(order_items, order)
        payment = paypalrestsdk.Payment(payment_data, api=paypal_api)
        if payment.create():
            order.payment_type = Order.PAY_PAYPAL
            order.payment_id = payment.id
            order.save(update_fields=['payment_type', 'payment_id'])
            
            return JsonResponse({
                'paymentID': payment.id
            })
        
        return JsonResponse({
            'paymentID': None
        })


class PayPalExecuteView(View):

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, *args, **kwargs):
        order = Order.objects.get(
            payment_type=Order.PAY_PAYPAL,
            payment_id=self.request.POST.get('paymentID'),
        )
        payment = paypalrestsdk.Payment.find(self.request.POST.get('paymentID'))
        if payment.execute({'payer_id': self.request.POST.get('payerID')}):
            order.paid = True
            order.save(update_fields=['paid'])
            purchase_mailing.delay(self.request.user.email, order.pk)
            return JsonResponse({
                'payment_status': 'ok'
            })
        return JsonResponse({
            'payment_status': 'fail'
        })


class PayView(PaymentView):
    template_name = 'payments/pay_liqpay.html'

    def get(self, request, *args, **kwargs):
        liqpay = LiqPay(settings.LIQPAY_PUBLIC_KEY, settings.LIQPAY_PRIVATE_KEY)
        order = self.get_object()
        if order.paid:
            return HttpResponse("HTTP 403 status code. Restricted Area", status=403)

        params = {
            'action': 'pay',
            'amount': str(order.total),
            'currency': 'UAH',
            'description': 'Покупка электроники',
            'order_id': order.u_id,
            'version': '3',
            'sandbox': 0, # sandbox mode, set to 1 to enable it
            'server_url': settings.LIQPAY_CALLBACK_URL, # url to callback view
        }
        signature = liqpay.cnb_signature(params)
        data = liqpay.cnb_data(params)

        return render(
            request,
            self.template_name,
            {
                'signature': signature,
                'data': data,
                'order': order,
            }
        )


@method_decorator(csrf_exempt, name='dispatch')
class PayCallbackView(View):

    def post(self, request, *args, **kwargs):
        liqpay = LiqPay(settings.LIQPAY_PUBLIC_KEY, settings.LIQPAY_PRIVATE_KEY)
        data = request.POST.get('data')
        signature = request.POST.get('signature')

        sign = liqpay.str_to_sign(settings.LIQPAY_PRIVATE_KEY + data + settings.LIQPAY_PRIVATE_KEY)
        if sign == signature:
            response = liqpay.decode_data_from_str(data)
            order = Order.objects.get(u_id=response['order_id'])
            order.json_response = response
            status = response['status']
            if status == 'success' or \
                    status == 'wait_accept' or \
                    status == 'wait_compensation':
                order.paid = True
                order.payment_id = response['payment_id']
                order.save()
                return HttpResponse('ok')

            order.save()
            return HttpResponse('payment error: see detail', code=405)

        return HttpResponse('signature error', code=405)

market/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from django.views import generic
from django.urls import reverse_lazy
from config import settings

from market.products.forms import UserForm


class RoomView(LoginRequiredMixin, TemplateView):
    active_tab = 'cart'
    template_name = 'users/room.html'


class RegisterView(generic.CreateView):
    model = settings.AUTH_USER_MODEL
    form_class = UserForm
    success_url = reverse_lazy('users:login')
    template_name = 'register.html'

market/templates/products/cart.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load i18n %}
{% block content %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_loader.css' %}" />
{% endblock %}
<div class="container cart_cont">
            <div id="cube-loader">
                <div class="caption">
                    <div class="cube-loader">
                        <div class="cube loader-1"></div>
                        <div class="cube loader-2"></div>
                        <div class="cube loader-4"></div>
                        <div class="cube loader-3"></div>
                    </div>
                 </div>
            </div>
      <div class="conteiner_korzina_null cart_mobile_version">
          <h2>Ваша корзина пуста</h2>
          <img src="{% static 'img/telega.png' %}" alt="">
      </div>      
     <div class="row artikul_cart artikul_cart_mobile">
            <div class="col-7 col-sm-7 col-md-7 col-lg-6">
                    Наименование
             </div>
             <div class="col-2 col-sm-2 col-md-2 col-lg-2 text_count">
                    Количество
            </div>
            <div class="col-1 col-sm-1 col-md-1 col-lg-2">
                   <p> Цена за 1 шт.</p>
            </div>
            <div class="col-2 col-sm-2 col-md-2 col-lg-2">
                <p> Итоговая цена</p>
            </div>
     </div>
     {% for product in cart_list %}

     <div class="row artikul_products" data-productIdRemove="{{ product.pk }}">

  
        <div class="col-12 col-sm-7 col-md-7 col-lg-6">
             <div class="row mobile_flex">
               <div class="col-2 col-sm-2 col-md-1 col-lg-1 mobile_musor">
                  <a href="#"><img product_id="{{ product.pk }}" src="{% static 'img/musor.png' %}" alt="" class="musor_img remove-from-cart">
                  </a>
                </div>
                <div class="col-3 col-sm-2 col-md-2 col-lg-2 mobile_img_products">
                    <div class="title_products">
                       <a href="{{ product.get_absolute_url }}">
                            {% thumbnail product.image "110x60" as im %}
                            <img src="{{ im.url }}">
                             {% endthumbnail %}
                        </a>
                    </div>
                </div> 
                <div class="col-6 col-sm-8 col-md-9 col-lg-9 mobile_description"> 
                   <div class="description_product"> 
                       <h3>
                         <a href="{{ product.get_absolute_url }}">
                            {{ product.name|title }}
                         </a>
                      </h3>
                    <p>
                        {{ product.description|safe|truncatechars:200 }}
                    </p>

                 </div>
              </div> 
              <div class="col-1 col-sm-1 col-md-1 col-lg-2 col_price col_price_mobile">
                <p class="price">{{ product.price }} грн</p>
              </div>
             </div>
            </div>
         
            <div class="col-2 col-sm-2 col-md-2 col-lg-2">
                   <div class="count_product cart_count_product">
                            <div class="minus_product cart_minus_product change-product-amount" product_id="{{ product.id }}">
                                <img src="{% static 'img/minus.png' %}" alt="">
                            </div>
                            <div class="cart_count_product_p">
                            <p
                                    class="cart-product-amount"
                                    product_count="{{ product.quantity }}"
                                    product_id="{{ product.id }}"
                            >
                                {{ product.quantity }}
                            </p>
                            </div>
                            <div class="plus_product cart_plus_product change-product-amount" product_id="{{ product.id }}">
                                <img src="{% static 'img/plus.png' %}" alt="">
                            </div>
                        </div>
                   <!-- <p class="price">{{ product.quantity }}</p>  -->
            </div>
     
            <div class="col-1 col-sm-1 col-md-1 col-lg-2 col_price">
                    <p class="price">{{ product.price }} грн</p>
            </div>
            <div class="col-2 col-sm-2 col-md-2 col-lg-2 col_price">
                <p id="total_product_price_{{ product.id }}" class="price">{{ product.total_price}} грн</p>
            </div>
     </div>
     {% endfor %}    
     <div class="row">
        <div class="col-12 total_sum">
                <button id="clear_cart" class="btn btn-primary">Очистить корзину</button>
                <script>
                     count_cart_item=$(".cart-item").length;
                </script>
          <div class="flex_total_sum">  
            <p id="total_cart_price" class="total">
            Всего к оплате :  {{ total }} грн
            <!-- <span class="glyphicon glyphicon-usd"></span> -->
            </p> 
        <a href="{% url 'payments:checkout' %}">
            <button {% if not total %}disabled{% endif %} class="btn btn-primary">
                 Оформить заказ
             </button>
         </a></div>
        </div>   
    </div>
</div>

    
{% endblock %}



{% block js_extras %}
    <script>
        var product;
    function change_product_amount_response(response) {
        console.log(response);
        if(response['status'] =='added') {
            var product_id = response['product_id'];
            $("#total_product_price_" + product_id).text(response['item_total_price'] + " грн");
            $("#total_cart_price").text("Всего к оплате :  " + response['total'] + " грн");
        }
    }
    $(document).ready(function() {
        $('.remove-from-cart').bind('click', function( event ) {
            
            product = $(this).attr('product_id');
            var request_url = "/products/" + product + "/add/to/cart/";

            var cart_request_data = {
                         product: product
                        };
         if($(".artikul_products").length<3){
            $(".footer").css({"position":"absolute","bottom" :"0px"}); 
          };
            //console.log(cart_request_data);
            send_ajax_request(request_url, cart_request_data, add_to_cart_response, "DELETE", "json");
        });
       $('.change-product-amount').bind('click', function( event ) {
            var product_id = $(this).attr('product_id');
            if(document.querySelector(".cont_1").clientHeight<390 ) {$(".footer").css({"position":"absolute","bottom" :"0px"});}
            var product_count = parseInt(
                                    $(".cart-product-amount").
                                    filter("[product_id ="+product_id+"]").
                                    attr("product_count")
                                );
            var request_url = "/products/" + product_id + "/add/to/cart/";

            var cart_request_data = {
                         product: product_id,
                         product_amount: product_count
                        };

            console.log(cart_request_data);
     

            send_ajax_request(request_url, cart_request_data, change_product_amount_response, "POST", "json");
        });
        $('#clear_cart').bind('click', function( event ) {
            if(document.querySelector(".cont_1").clientHeight<390) {$(".footer").css({"position":"absolute","bottom" :"0px"});}
            send_ajax_request("/products/clear_cart/", {}, clear_cart_response, "DELETE", "json");

            $(".footer").css({"position":"absolute","bottom" :"0px"}); 
          
        });
    });
</script>
{% endblock js_extras %}

market/templates/products/grade_list.html
<!-- {% extends "base.html" %}
{% block content %}

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">{{ grade|title }}</h3>
  </div>
  <div class="panel-body">
    {% include 'additional_parts/products/products_imagination.html' with products=grade_list %}
  </div>
</div>
{% include 'additional_parts/products/pagination.html' with   page_obj=page_obj %}

{% endblock content %} -->

market/templates/products/product_detail.html
{% extends "category_base.html" %}
{% load thumbnail %}
{% load static %}

{% block main_body %}
<div class="col-7 col-sm-8 col-md-9  col-lg-9">
    <div class="row">
            <div class="flex_title">
                    <h4 class="title_product">
                        {{ product.name }}
                    </h4>
                 
                </div>
        <div class="col-12 col-sm-6 col-md-6  col-lg-6">
            <div class="col-md-12">
                <div class="galery">
            {% if  product.in_stock %}<p style="color : #038a27;margin-left: 1%;font-size: 13px">Есть в наличии</p> {% else %} <p 
            product_id_noStok="{{ product.id }}" class="in_stok_detail" style="color : #ba0f20;margin-left: 1%;font-size: 13px">Нет на складе</p> {% endif %}
                    <img src="" alt="" class="active_big">
                    <div class="img_bottom">
                        {% thumbnail product.image "1000x1000" as im %}
                            <img class="img_product_detail active_img" src="{{ im.url }}">
                        {% endthumbnail %}
                        {% for image in product.images.all %}
                            {% thumbnail image.image "1000x1000" as im %}
                                    <img src="{{ im.url }}" class="img_product_detail">
                            {% endthumbnail %}
                        {% endfor %}
                    </div>
                </div>
                <div class="mobile_show_comment">
                <div class="comment_otziv">
                    {% for comment in comments_ %}
                        {% include "additional_parts/products/product_detail_comment.html"  with comment=comment %}
                    {% endfor %}
                    <button class="show_user">Показать все комментарии</button>
                </div>
                <div id="js-product-detail-comment"></div>
                <div class="add_otziv_img">
                    <p>Добавте</p>
                        <img src="{% static 'img/otziv.png' %}" alt="" class="ostav_otziv">
                    <p>отзыв</p>
                </div>
                <p class="error_otsiv"></p>
                <div class="form_add_otziV">
                    <div class="form-group">
                        <input type="text" class="form-control js-comments" id="user_name"
                               placeholder="{{ request.user.username }}" readonly="readonly"
                               value="{{ request.user.username }}" name="user_name">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control content " id="user_comment"
                                  name="user_comment" rows="4"
                                  maxlength="500" placeholder="Добавте отзыв">
                        </textarea>
                    </div>
                    <input type="submit" id="add_comment_btn" class="subm_otziv"
                           value="Отправить"
                           name="add_comment">
                </div>
            </div>
            </div>
        </div>

        <div class="col-12 col-sm-6 col-md-6  col-lg-6 detail_product_block">
            <div class="row statusBar_products">
                <div class="col-12 col-sm-12 col-md-12 col-lg-11 statusBar_products_col">
                    
                    <div class="likes">
                            <p class="span_price"> {{ product.price }} грн. </p>
                    </div>
                    <div class="likes">
                        {% if  product.in_stock %}
                        <input type="submit" value="купить"
                        class="button_orders zapis detail_button_orders" id="add_to_cart"
                        >
                        {% else %}
                        <input type="submit" value="купить"
                        class="button_orders zapis detail_button_orders hidden_button hidden_button_detail" id="add_to_cart"
                        >
                        {% endif %} 
                   </div>
                </div>
            </div>
            <p>{{ product.description | safe  }}</p>
        </div>
    </div>
</div>

{% endblock main_body %}




{% block js_extras %}
<script>
    function comment_request() {
        var text = $('#user_comment').val();
        var product = "{{ product.pk }}";
        var request_url = "{% url 'products:product_detail' category_slug=product.subcategory.category.slug subcategory_slug=product.subcategory.slug product_slug=product.slug %}";

        var data = {
                     text: text,
                     product: product
                    };

        send_ajax_request(request_url, data, front_change_comments_bar);
    }

    function add_to_cart() {
        var product = "{{ product.pk }}";
        var product_amount = $('#product_amount').val();
        var request_url = "{% url 'products:add_to_cart' product_pk=product.pk %}"

        var data = {
                     product: product,
                     product_amount: product_amount
                   };
        send_ajax_request(request_url, data, add_to_cart_response);
    }

    function front_change_comments_bar(ajax_response) {
        console.log(ajax_response);
        if (ajax_response['data']) {
            $('#js-product-detail-comment')[0].innerHTML += ajax_response['data'];
            $('#user_name').val('');
            $('#user_comment').val('');
        }
        if (ajax_response['errors']) {
            var errors = ajax_response['errors'];
            console.log(errors);
            console.log("You must be login");
        }
    }
    $(document).ready(function() {
        $('#add_comment_btn').on('click', comment_request);
        $('#add_to_cart').on('click', add_to_cart);
    });
</script>

{% endblock js_extras %}