config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from market.products.views import CategoryListView


urlpatterns = [
    url(r'^$', CategoryListView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^products/', include(("market.products.urls", "products"), namespace="products")),
    url(r'^users/', include(("market.users.urls", "users"), namespace="users")),
    url(r'^payments/', include(("market.payments.urls", "payments"), namespace="payments")),
    url(r'^myadmin/', include(("market.myadmin.urls", "myadmin"), namespace="myadmin")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

market/myadmin/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView


from rest_framework_nested import routers
from rest_framework_swagger.views import get_swagger_view


from market.myadmin.views import (
    OrderViewSet,
    OrderItemViewSet,
)


schema_view = get_swagger_view(title='Pastebin API')  # pylint: disable=invalid-name


simple_router = routers.SimpleRouter()

simple_router.register(r'orders', OrderViewSet, basename='orders')
simple_router.register(r'order_items', OrderItemViewSet, basename='order_items')


urlpatterns = [
    url(r'^', include(simple_router.urls)),
    url(r'^$', schema_view),
    url(r'^index/$', TemplateView.as_view(template_name='myadmin/index.html'), name='myadmin'),
]

market/products/urls.py
from django.conf.urls import url
from market.products import views


urlpatterns = [
    url(r'^info/$', views.InfoView.as_view(), name='info'),
    url(r'^search/$', views.search_products, name='search_products'),
    url(r'^cart/$', views.CartView.as_view(), name='cart'),
    url(r'^clear_cart/$', views.ClearCart.as_view(), name='clear_cart'),
    url(
        r'^(?P<product_pk>[0-9]+)/add/to/cart/$',
        views.AddToCartView.as_view(),
        name='add_to_cart'
    ),
    url(
        r'^(?P<category_slug>.+)/(?P<subcategory_slug>.+)/(?P<product_slug>.+)/$',
        views.ProductDetailView.as_view(),
        name='product_detail'
    ),
    url(
        r'^(?P<category_slug>.+)/(?P<subcategory_slug>.+)/$',
        views.SubCategoryDetailView.as_view(),
        name='subcategory_detail'),
]

market/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from market.users.views import RoomView, RegisterView

urlpatterns = [
    url(r'^room/$', RoomView.as_view(), name='room'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
]

market/blog/models.py
from django.db import models
from django.conf import settings

from pygments import highlight
from pygments.lexers import (
    PythonLexer,
    CLexer,
    CppLexer,
    BashLexer,
)

from pygments.formatters import HtmlFormatter


UserModel = settings.AUTH_USER_MODEL


class Post(models.Model):
    title = models.fields.CharField(max_length=255, null=False,
                                    blank=False)
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE,
                               blank=False, null=False,)
    text = models.fields.CharField(max_length=2000, null=False,
                                   blank=False)


class Snippet(models.Model):
    CODE_LANG = (
        ('c', 'c'),
        ('cpp', 'cpp'),
        ('python', 'python'),
        ('bash', 'bash'),
    )
    LEXERS = {
        'c': CLexer,
        'cpp': CppLexer,
        'python': PythonLexer,
        'bash': BashLexer,
    }

    lang = models.CharField(choices=CODE_LANG, default='python',
                            max_length=50, blank=False, null=False)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE,
        null=False, blank=False, related_name='snippets')
    code = models.CharField(max_length=2000, null=False,
                            blank=False)

    def __str__(self):
        formatted_code = highlight(self.code,
                                   self.LEXERS[str(self.lang)](),
                                   HtmlFormatter())
        return '%s\n%s' % (self.lang, formatted_code)

market/products/models.py
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone


from model_utils import Choices
from model_utils.models import TimeStampedModel

from ckeditor.fields import RichTextField
from config import settings


class Category(models.Model):
    """Product category model"""

    name = models.CharField(_('Name'), max_length=200)
    slug = models.SlugField(_('Slug'), unique=True)

    PARAMS = Choices(
        ('following', 'following'),
        ('price_to', 'price_to'),
        ('price_from', 'price_from'),
    )

    def __str__(self):
        return self.name
        

class SubCategory(models.Model):
    """Subcategory for category model"""

    name = models.CharField(max_length=200)
    slug = models.SlugField(_('Slug'), unique=True)

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='subcategories',
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            'products:subcategory_detail', 
            kwargs={
                'category_slug': self.category.slug,
                'subcategory_slug': self.slug
        })


class Product(TimeStampedModel):
    """Product model"""

    POPULAR_CHOICES = (
        ('F', 'not_popular'),
        ('T', 'popular')
    )

    name = models.CharField(_('Name'), max_length=200)
    code = models.CharField(
        null=False,
        blank=False,
        max_length=255,
    )
    in_stock = models.BooleanField(default=False)
    slug = models.SlugField(_('Slug'), unique=True)
    price = models.DecimalField(_('Price'), decimal_places=2, max_digits=9)
    description = RichTextField(_('Description'), blank=True)
    subcategory = models.ForeignKey(
        SubCategory,
        related_name='products',
        on_delete=models.CASCADE,
    )
    image = models.ImageField(upload_to='products', blank=True)
    popular = models.CharField(
        max_length=1,
        choices=POPULAR_CHOICES,
        blank=False,
        default='F',
    )
 
    class Meta:
        ordering = ('-created', )

    def get_absolute_url(self):
        return reverse('products:product_detail', kwargs={
            'category_slug': self.subcategory.category.slug,
            'subcategory_slug': self.subcategory.slug,
            'product_slug': self.slug
        })

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    image = models.ImageField(upload_to='products', blank=True)
    product = models.ForeignKey(
        Product,
        related_name='images',
        on_delete=models.CASCADE, 
    )


class Like(TimeStampedModel):
    product = models.ForeignKey(
        Product,
        related_name='likes',
        on_delete=models.CASCADE,         
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='likes',
        on_delete=models.CASCADE,     
    )

    class Meta:
        unique_together = (
            ('product', 'user'),
        )

    def __str__(self):
        return '{} from {}'.format(self.product, self.user)


class Comment(TimeStampedModel):
    product = models.ForeignKey(
        Product,
        blank=False,
        null=False,
        related_name='comments',
        on_delete=models.CASCADE,     
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=False,
        null=False,
        related_name='comments',
        on_delete=models.CASCADE, 
    )

    text = models.TextField(_('Comment'))


class Checkout(models.Model):
    phone = models.CharField(
        max_length=255,
        null=False,
        blank=False,
    )
    payment_type = models.CharField(
        max_length=30,
        choices=[
            ('stripe', 'Stripe'),
            ('paypal', 'PayPal'),
            ('liqpay', 'Liqpay')
        ],
        null=False,
        blank=False,
    )
    fio = models.CharField(
        max_length=255,
        null=True,
        blank=True,
    )
    email = models.EmailField(null=True)
    comment = models.CharField(
        max_length=500,
        null=False,
        blank=False,
    )

    def __str__(self):
        return 'Checkout({}, {}, {}, {}, {})'.format(
            self.pk,
            self.phone,
            self.fio,
            self.email,
            self.comment,
        )


class Order(TimeStampedModel):
    PAY_STRIPE = 'stripe'
    PAY_PAYPAL = 'paypal'
    PAY_LIQPAY = 'liqpay'

    DEFAULT_PAYMENT_TYPE = 'liqpay'

    total = models.DecimalField(
        _('Total'),
        decimal_places=2,
        max_digits=9,
    )
    paid = models.BooleanField(default=False)
    approved = models.BooleanField(default=False)
    payment_type = models.CharField(
        choices=[
            ('stripe', 'Stripe'),
            ('paypal', 'PayPal'),
            ('liqpay', 'Liqpay')
        ],
        max_length=255,
    )
    payment_id = models.CharField(
        blank=True,
        max_length=255,
    )
    u_id = models.CharField(
        blank=False,
        null=False,
        max_length=255,
    )
    json_response = JSONField(null=True, blank=True)
    checkout = models.ForeignKey(
        Checkout,
        on_delete=models.CASCADE,
        null=False,
    )

    progress = models.CharField(
        max_length=2,
        choices=(
            ('f', 'wait'),
            ('t', 'ok'),
        ),
        default='f',
    )
    datetime = models.DateTimeField(null=False, default=timezone.now())

    def __str__(self):
        return 'Order_{}'.format(self.pk)


class CartItem(TimeStampedModel):
    product = models.ForeignKey(
        Product,
        related_name='cart',
        on_delete=models.CASCADE,
    )
    order = models.ForeignKey(
        Order,
        related_name='cart_items',
        on_delete=models.CASCADE,
    )
    quantity = models.PositiveIntegerField(_('Amount'))
    total = models.DecimalField(
        _('Total'),
        decimal_places=2,
        max_digits=9,
    )

    def __str__(self):
        return 'CartItem for {}'.format(self.order)


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        related_name='items',
        on_delete=models.CASCADE,     
    )
    code = models.CharField(
        null=False,
        blank=False,
        max_length=255,
    )
    product = models.ForeignKey(
        Product,
        null=True,
        blank=True,
        related_name='+',
        on_delete=models.SET_NULL,
    )
    name = models.CharField(blank=False, null=False, max_length=200)
    price = models.DecimalField(_('Price'), decimal_places=2, max_digits=9)
    description = RichTextField(_('Description'), blank=True)
    subcategory = models.CharField(blank=False, null=False, max_length=200)

    quantity = models.PositiveIntegerField(_('Quantity'))
    total = models.DecimalField(_('Total'), decimal_places=2, max_digits=9)

market/payments/forms.py
from django import forms
from market.products.models import Checkout


class OrderForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    name = forms.CharField(max_length=50, required=True)
    surname = forms.CharField(max_length=50, required=True)
    phone = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(required=False)
    address = forms.CharField(max_length=255, required=True)


class CheckoutForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fio'].required = False
        self.fields['email'].required = False
        self.fields['comment'].required = True

    class Meta:
        model = Checkout
        fields = (
            'phone',
            'fio',
            'email',
            'comment',
            'payment_type'
        )

market/products/forms.py
from django import forms
from django.contrib.auth import get_user_model

from market.products.models import Product, Comment


User = get_user_model()


class LikeForm(forms.Form):
    user = forms.ModelChoiceField(
        User.objects.all(),
        required=False
    )
    product = forms.ModelChoiceField(Product.objects.all())


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['user', 'product', 'text']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'phone', 'email', 'password', 'image']
        widgets = {
            'username': forms.TextInput(attrs={
                'example': 'example',
                'class': 'wrap-input100 validate-input m-b-16 inputCustom',
                'placeholder': 'Укажите имя',
            }),
            'phone': forms.TextInput(attrs={
                'example': 'example',
                'class': 'wrap-input100 validate-input m-b-16 inputCustom',
                'placeholder': 'Укажите телефон',
            }),
            'email': forms.TextInput(attrs={
                'example': 'example',
                'class': 'wrap-input100 validate-input m-b-16 inputCustom',
                'placeholder': 'Укажите адрес эл.почты',
            }),
            'password': forms.TextInput(attrs={
                'type':'password',
                'example': 'example',
                'class': 'wrap-input100 validate-input m-b-16 inputCustom password_input',
                'placeholder': 'Пароль',
            }),
           
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

market/blog/views.py
from rest_framework.authentication import BasicAuthentication
from rest_framework import viewsets, views

from market.products.models import (
    Order,
    OrderItem,
)

from market.myadmin.pagination import StandardResultsSetPagination
from market.myadmin.permissions import IsAdminOrFYou
from market.myadmin.filters import (
    StatusFilterBackend,
    PaidStatusFilterBackend,
    OrderItemOrderPkFilterBackend,
)
from market.myadmin.serializers import (
    OrderSerializer,
    OrderItemSerializer,
)


class OrderViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderSerializer
    queryset = Order.objects.all()
    filter_backends = (
        StatusFilterBackend,
        PaidStatusFilterBackend
    )
    pagination_class = StandardResultsSetPagination

    def get_queryset(self, *arg, **kwargs):
        # from time import sleep
        # sleep(1)
        return super().get_queryset(*arg, **kwargs)


class OrderItemViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderItemSerializer
    queryset = OrderItem.objects.all()
    filter_backends = (
        OrderItemOrderPkFilterBackend,
    )
    pagination_class = StandardResultsSetPagination

market/myadmin/views.py
from rest_framework.authentication import BasicAuthentication
from rest_framework import viewsets, views

from market.products.models import (
    Order,
    OrderItem,
)

from market.myadmin.pagination import StandardResultsSetPagination
from market.myadmin.permissions import IsAdminOrFYou
from market.myadmin.filters import (
    StatusFilterBackend,
    PaidStatusFilterBackend,
    OrderItemOrderPkFilterBackend,
)
from market.myadmin.serializers import (
    OrderSerializer,
    OrderItemSerializer,
)


class OrderViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderSerializer
    queryset = Order.objects.all().order_by('-id')
    filter_backends = (
        StatusFilterBackend,
        PaidStatusFilterBackend
    )
    pagination_class = StandardResultsSetPagination

    def get_queryset(self, *arg, **kwargs):
        # from time import sleep
        # sleep(1)
        return super().get_queryset(*arg, **kwargs)


class OrderItemViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAdminOrFYou, )
    serializer_class = OrderItemSerializer
    queryset = OrderItem.objects.all()
    filter_backends = (
        OrderItemOrderPkFilterBackend,
    )
    pagination_class = StandardResultsSetPagination

market/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from django.views import generic
from django.urls import reverse_lazy
from config import settings

from market.products.forms import UserForm


class RoomView(LoginRequiredMixin, TemplateView):
    active_tab = 'cart'
    template_name = 'users/room.html'


class RegisterView(generic.CreateView):
    model = settings.AUTH_USER_MODEL
    form_class = UserForm
    success_url = reverse_lazy('users:login')
    template_name = 'register.html'

market/templates/category_base.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<div class="row block_category">
     <!-- кнопка вызова категорий в мобильной версии -->
     <button class="click_category_mobile">КАТЕГОРИИ</button>
    <div class="col-sm-4 col-md-3  col-lg-3 category_yes_now_mobile mobile_padding">
       <!-- блок для вывода категорий и подкатегорий -->
        <div class="list-group">
            <button type="button" class="list-group-item list-group-item-action mobile_button_category" style="background-color: #428bca;color: white">

                    <h3 class="panel-title">КАТЕГОРИИ</h3>
                    <img src="{% static 'img/close.png' %}" alt="" class="close_category">

            </button>
            {% for category in category_list %}
                    <button type="button" class="list-group-item list-group-item-action category_button" data-id="{{category.id}}">
                        <div class="row ">
                            <div class="col-md-12 button_category">
                                <h5 class="list-group-item-heading">{{ category.name|title }}</h5>
                                <img src="{% static 'img/arrow_category.png' %}"
                                     alt="" class="arrow_category" data-id="{{category.id}}">
                            </div>
                        </div>
                    </button>
                    {% for sub_category in category.subcategories.all %}

                     <!-- {% if subcategory.slug == active %}
                            attr-1="{{ active_tab }}"
                            {% endif %} -->
                        <a href="{{ sub_category.get_absolute_url }}" class="a_subcategory">
                            <button type="button" class="list-group-item list-group-item-action subcategory"
                                    data-id="{{category.id}}" data-tab="{{ active_tab }}">
                                    <div class="row ">
                                        <div class="col-md-9">
                                            {{ sub_category.name|title }}<br>
                                        </div>
                                    </div>
                            </button>
                        </a>
                    {% endfor %}
            {% endfor %}
        </div>
    </div>


    {% block main_body %}
    {% endblock main_body %}
    
{% endblock content %}

market/templates/chat_base.html
<a href="https://m.me/640693163078039" target="_blank">
    <div class="facebook">
        
    </div>
    </a>

market/templates/footer.html
{% load static %}

<footer class="footer dekstop_version">
    <div class="container-fluid">
        <div class="row footer_content">
            <div class="col-12 navigation">
                <ul class="ul_navigation">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'products:cart' %}">Корзина</a></li>
                    <li><a href="{% url 'products:info' %}">Оферта и Политика конфиденциальности</a></li>
                    <li><a href="{% url 'users:login' %}">Войти</a></li>
                    <li>
                    <ul class="social_ul_footer">
                            <li class="item_social"><a href=""><img src="{% static 'img/facebook_footer.png' %}" alt="" class="footer_social"></a></li>
                            <li class="item_social"><a href=""><img src="{% static 'img/youtube_footer.png' %}" alt="" class="footer_social"></a></li>
                            <li class="item_social"><a href=""><img src="{% static 'img/whats_footer.png' %}" alt="" class="footer_social"></a></li>
                            <li class="item_social"><a href=""><img src="{% static 'img/instagram_footer.png' %}" alt="" class="footer_social"></a></li>
                        </ul></li>
                    
                </ul>
            </div>
        <div class="row">
                <div class="col-xs-4 col-md-3 col-lg-3 container_logo_footer">
                    <div class="logo_footer"> </div> 
                    <h2 class="logo_title_footer">IOT COMPANY</h2>
                </div>
                <div class="col-xs-4 col-md-5 col-lg-5 form_footer">
                        <!-- <h5>Обратный звонок</h5> -->

                        <form method="" action="" class="login">
                            <p>
                                <input type="text" name="login" id="login" placeholder ="Укажите имя" style="color: black;font-size: 17px">
                            </p>
                            <p>
                                <input type="tel" name="tel" id="tel" placeholder="Номер телефона" style="color: black;font-size: 17px">
                            </p>
                            <p class="login-submit">
                                <button type="submit" class="login-button">Войти</button>
                            </p>
                        </form>
                        <div class="viza_card">
                            <img src="{% static 'img/viza.png' %}" alt="" class="viza">
                            <img src="{% static 'img/paypal.png' %}" alt="" class="paypall">
                        </div>
                        <p>поддерживаемые платежные системы</p>

                </div>
                <div class="col-xs-4 col-md-4 col-lg-4 work_grafik_footer">
                        <h4>График работы:</h4>
                        <p>В будние:    с 8:00 до 21:00 <br>Суббота:   с 9:00 до 20:00 <br>Воскресенье:  c 10:00 до 19:00</p>
                        <p>тел.: (095) 508 1131</p>
                        <p>Email: levtolstoy123123@gmail.com</p>
                </div>
        </div>
        </div>
    </div>
</footer>

<!-- футер для мобильной версии сайта -->
<footer class="footer mobile_version">
        <div class="container mobile_conteiner">
            <h5>Позвонить (095) 508 1131</h5>
      
            <div class="container_logo_footer mobile_logo_footer">
                    <div class="logo_footer"> </div> 
                    <h2 class="logo_title_footer">IOT COMPANY</h2>
            </div>
        </div>
    
</footer>

market/templates/header.html
{% load static %}
<div class="container-fluid menu_cont">
  <div class="row top">
    <div class="col-3 col-sm-3 col-md-3  col-lg-2">
      <p class="contact">(095) 508 1131</p>
    </div>
    <div class="col-3 col-sm-5 col-md-5  col-lg-5 contact_href">
      <p class="hover_contact">О нас</p> 
      <a href="{% url 'products:info' %}" class="delivery">Оферта и Политика конфиденциальности</a>

    </div>
    <div class="col-0 col-sm-0 col-md-0  col-lg-2">

    </div>
      <div class="col-6 col-sm-4 col-md-4  col-lg-3 sign_in">
        {% if request.user.username %}
          <a href="{% url 'users:room' %}" class="login_in">
            <p class="login_out_in">
              {{ request.user.username }}
            </p>
          </a>
        {% else %}
          <a href="{% url 'users:room' %}" class="login_in">
            <p class="login_out_in">Вход</p>
          </a>
        {% endif %}
        {% if request.user.username %}
         <div class="logaut_div">
             <img src="{% static 'img/login.png' %}" alt="" class="logout_img">
             <a href="{% url 'users:logout' %}" class="logaut_a">
              Выйти
            </a>
          </div>
          {% else %}
          <div class="logaut_div" >
            <a href="{% url 'users:register' %}" class="registr">
             Регистрация
           </a>
           <img src="{% static 'img/registration.png' %}" alt="" class="logout_img registration_img">
         </div>
      {% endif %}
      </div>
     
    </div>

    <div class="row bottom">
      <div class="col-3 col-sm-3 col-md-2  col-lg-2">
        <a class="navMenu_href" href="{% url 'home' %}">

        </a>
      </div>
      <div class="col-7 col-sm-7 col-md-8 col-lg-8 searchDiv max_menu_searchDiv">
        <form action="" method="post" class="search">
          <input type="search" name="" placeholder="поиск" class="input" id="searchInput"/>
          <input type="submit" name="" value="НАЙТИ" class="submit" />
        </form>

      </div>
      <a class=""  href="{% url 'products:cart' %}">
        <div class="col-2 col-sm-2 col-md-2  col-lg-2">
            <img src="{% static 'img/korzina_header.png.png' %}" alt="" class="korzina_img">
            <!-- <div class="korzina_img_countProduct">
              <p>{{ item.amount }}</p>
            </div> -->
        </div>
      </a>
    </div>

</div>

<!-- меню для мобильной версии сайта -->
<div class="container-fluid menu_cont_mobile">
  <nav class="navbar navbar-expand-lg navbar-light bg-light minMenu">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="searchDiv">
      <form action="" method="post" class="search">
        <input type="search" name="" placeholder="я ищу..." class="input" id="searchInput"/>
      </form>
    </div>
    <a class="mobile_menu_href"  href="{% url 'products:cart' %}">
          <img src="{% static 'img/korzina_mobileMenu.png' %}" alt="" class="korzina_img">
          <!-- <div class="korzina_img_countProduct">
            <p>{{ item.amount }}</p>
          </div> -->
    </a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">О нас</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'products:info' %}">Оферта и Политика конфиденциальности</a>
        </li>
         <li class="nav-item">
          <a class="nav-link " href="{% url 'users:room' %}">Вход</a>
        </li>
      </ul>
    </div>
  </nav>
</div>
    </div>
    

market/templates/login.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<div class="errors">
<p class="errornote">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p></div>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<div class="errors">
<p class="errornote">
    {{ error }}
</p></div>
{% endfor %}
{% endif %}

<div id="content-main">

{% if user.is_authenticated %}
<div class="errors"></div>
<p class="errornote">
{% blocktrans trimmed %}
    You are authenticated as {{ username }}, but are not authorized to
    access this page. Would you like to login to a different account?
{% endblocktrans %}
</p>
{% endif %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}" />
{% endblock %}
<form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
    <div class="limiter">
        <div class="container-login100">
            <a href="/" class="home_registor_aus">На главную</a>
          <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
            <form class="login100-form validate-form flex-sb flex-w">
              <span class="login100-form-title p-b-32">
                Авторизация
              </span>
              <span class="txt1 p-b-11">
                Логин
              </span>
              <div class="wrap-input100 validate-input m-b-36" data-validate = "Username is required">
                  {{ form.username }}
                  <span class="focus-input100"></span>
                </div>
              
              <span class="txt1 p-b-11">
                Пароль
              </span>
          
              <div class="form-row">
                  {{ form.password }}
                </div>
              
              <div class="flex-sb-m w-full p-b-48">
                <div class="contact100-form-checkbox">
                  
                </div>
    
                <div>
                  <a href="#" class="txt3">
                    Забыли пароль?
                  </a>
                </div>
              </div>
          
              <div class="container-login100-form-btn">
                <input class="login100-form-btn" type="submit" value="{% trans 'Войти' %}">
                </input>
                <a href="{% url 'users:register' %}">
                <input class="login100-form-btn registration" type="submit" value="{% trans 'Регистрация' %}">
              </input></a>
              </div>

          
    
            </form>
          </div>
        </div>
      </div>

  {% url 'admin_password_reset' as password_reset_url %}
  {% if password_reset_url %}
  <div class="password-reset-link">
    <a href="{{ password_reset_url }}">{% trans 'Forgotten your password or username?' %}</a>
  </div>
  {% endif %}
  <div class="submit-row">
  
  </div> 
</form>

</div>
{% endblock %}